version: "2"

services:
  database:
    image: mongo:3.4
    volumes:
      - "${DATA_PERSISTENCE_DIRECTORY}/database:/data/db"

  web_server:
    build:
      context: ../..
      dockerfile: devops/docker/Dockerfile
      args:
        GIRDER_API_ROOT: ${GIRDER_API_ROOT}
        GIRDER_STATIC_PUBLIC_PATH: ${GIRDER_STATIC_PUBLIC_PATH}

    ports:
      - "${PORT}:8080"
    links:
      - database
    volumes:
      - "${DATA_PERSISTENCE_DIRECTORY}/assetstore:/assetstore"
      - "${PATH_TO_MOUNT_0}"
      - "${PATH_TO_MOUNT_1}"
    command:
      [
        "database:27017",
        "admin_name=${GIRDER_ADMIN_NAME} admin_pass=${GIRDER_ADMIN_PASS} admin_email=${GIRDER_ADMIN_USER_EMAIL} smtp_server=${GIRDER_SMTP_RELAY} smtp_port=${GIRDER_SMTP_PORT} smtp_encryption=${GIRDER_SMTP_CRYPTO} smtp_username=${GIRDER_SMTP_USER} smtp_password=${GIRDER_SMTP_PASSWD} server_url_in_email=${SERVER_URL_IN_EMAIL} sender_address=${SENDER_ADDRESS} sample_data=${SAMPLE_DATA} session_timeout=${MIQA_SESSION_TIMEOUT}",
      ]

  smtp-relay:
    image: hongkongkiwi/postfix-smtp-relay:latest
    links:
      - web_server
    environment:
      - ALLOWED_SENDER_DOMAINS=${ALLOWED_SENDER_DOMAINS}
