version: "2"

services:
  database:
    image: mongo:3.4
    volumes:
      - "${DATA_PERSISTENCE_DIRECTORY}/database:/data/db"

  web_server:
    build:
      context: ../..
      dockerfile: devops/docker/girder/Dockerfile
    ports:
      - "${PORT}:8080"
    links:
      - database
    command: --host 0.0.0.0 --database mongodb://database:27017/girder
    volumes:
      - "${DATA_PERSISTENCE_DIRECTORY}/assetstore:/assetstore"
      - "${PATH_TO_MOUNT}"

  provision:
    build:
      context: ../..
      dockerfile: devops/docker/provision/Dockerfile
    links:
      - database
      - web_server
    command:
      [
        "ghost=web_server gport=8080 gscheme=http assetstore=/assetstore admin_name=${GIRDER_ADMIN_NAME} admin_pass=${GIRDER_ADMIN_PASS} smtp_server=smtp-relay smtp_port=587 smtp_encryption=none smtp_username= smtp_password= server_url_in_email=${SERVER_URL_IN_EMAIL} sender_address=${SENDER_ADDRESS}"]

  smtp-relay:
    image: hongkongkiwi/postfix-smtp-relay:latest
    links:
      - web_server
    environment:
      - ALLOWED_SENDER_DOMAINS=${ALLOWED_SENDER_DOMAINS}
